### ISSUE TITLE
Missing Libraries?

### ISSUE THREAD

**Issue by mkumpf** [WebFlight/PdfParser#1]
I was excited to see this module in the appstore!

I installed it in a new (almost empty) project.  This is the only appstore module installed in this project.  When I try to call the java action GetPDFContent, I get the following error message:

_Error in execution of monitored action 'RegularClientAction' (execution id: 1553558347207-6, execution type: CLIENT).
 NoClassDefFoundError occurred for class 'org/slf4j/LoggerFactory'. Please make sure the userlib folder of
 your project includes the correct library which contains this class._

The stack trace starts like this
_java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.apache.tika.parser.journal.GrobidRESTParser.<clinit>(GrobidRESTParser.java:40)
	at org.apache.tika.parser.journal.JournalParser.parse(JournalParser.java:59)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.Tika.parseToString(Tika.java:527)
	at pdfparser.impl.PdfParser.getPdfContent(PdfParser.java:21)
	at pdfparser.actions.GetPDFContent.executeAction(GetPDFContent.java:46)
	at pdfparser.actions.GetPDFContent.executeAction(GetPDFContent.java:24)_

What am I missing?

**Comment by WardBrink** [comment]
Thank you for your feedback, I'm gonna look into it and will let you know once I fix it.

**Comment by WardBrink** [comment]
I just released a new version of this module. You can download it under the _Releases_ tab in the repository. Will upload it to the Mendix app store soon too. Let me know if it does what you need.
